services:
  ros2_humble_gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_humble_gazebo_harmonic
    network_mode: "host"
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ros2_humble_ws/src:/ros2_humble_ws/src
